# Generated by Django 4.2.7 on 2023-11-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
