# Generated by Django 4.2.7 on 2023-11-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_room_settlement_reservation_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='discount',
            field=models.ManyToManyField(to='db.discount'),
        ),
    ]
