# Generated by Django 4.2.7 on 2023-11-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='check_out_date',
            field=models.DateField(null=True),
        ),
    ]
