# Generated by Django 4.2.7 on 2023-11-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_alter_settlement_check_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_close',
            field=models.BooleanField(default=False),
        ),
    ]
