# Generated by Django 4.2.7 on 2023-11-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_reservation_is_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_close',
        ),
    ]
