# Generated by Django 4.2.7 on 2023-11-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0012_alter_order_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
