# Generated by Django 4.2.7 on 2023-11-06 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0013_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.user')),
            ],
        ),
    ]
