# Generated by Django 4.2.7 on 2023-11-09 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0017_alter_order_room_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user_id',
            new_name='user',
        ),
    ]
