# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_user_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from defes import create_user_win_defes


class create_user_win_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 600))
        MainWindow.setMaximumSize(QtCore.QSize(600, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 600, 600))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/resep.jpg"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 581, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: DarkBlue ;\n"
                                   "border: 3px solid bleak;\n"
                                   "border-radius: 20px;\n"
                                   "background-color: rgb(238, 238, 238);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.first_name_label = QtWidgets.QLabel(self.centralwidget)
        self.first_name_label.setGeometry(QtCore.QRect(70, 90, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.first_name_label.setFont(font)
        self.first_name_label.setStyleSheet("color: DarkBlue ;\n"
                                            "border: 3px solid bleak;\n"
                                            "border-radius: 20px;\n"
                                            "background-color: rgb(238, 238, 238);")
        self.first_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.first_name_label.setObjectName("first_name_label")
        self.last_name_label = QtWidgets.QLabel(self.centralwidget)
        self.last_name_label.setGeometry(QtCore.QRect(70, 150, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.last_name_label.setFont(font)
        self.last_name_label.setStyleSheet("color: DarkBlue ;\n"
                                           "border: 3px solid bleak;\n"
                                           "border-radius: 20px;\n"
                                           "background-color: rgb(238, 238, 238);")
        self.last_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.last_name_label.setObjectName("last_name_label")
        self.err_label = QtWidgets.QLabel(self.centralwidget)
        self.err_label.setGeometry(QtCore.QRect(10, 400, 581, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.err_label.setFont(font)
        self.err_label.setStyleSheet("color: rgb(231, 0, 0);")
        self.err_label.setText("")
        self.err_label.setAlignment(QtCore.Qt.AlignCenter)
        self.err_label.setObjectName("err_label")
        self.first_name_text = QtWidgets.QLineEdit(self.centralwidget)
        self.first_name_text.setGeometry(QtCore.QRect(250, 90, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.first_name_text.setFont(font)
        self.first_name_text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.first_name_text.setStyleSheet("color: DarkBlue ;\n"
                                           "border: 3px solid bleak;\n"
                                           "border-radius: 20px;\n"
                                           "background-color: rgb(238, 238, 238);")
        self.first_name_text.setAlignment(QtCore.Qt.AlignCenter)
        self.first_name_text.setObjectName("first_name_text")
        self.last_name_text = QtWidgets.QLineEdit(self.centralwidget)
        self.last_name_text.setGeometry(QtCore.QRect(250, 150, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.last_name_text.setFont(font)
        self.last_name_text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.last_name_text.setStyleSheet("color: DarkBlue ;\n"
                                          "border: 3px solid bleak;\n"
                                          "border-radius: 20px;\n"
                                          "background-color: rgb(238, 238, 238);")
        self.last_name_text.setAlignment(QtCore.Qt.AlignCenter)
        self.last_name_text.setObjectName("last_name_text")
        self.create_butt = QtWidgets.QPushButton(self.centralwidget)
        self.create_butt.setGeometry(QtCore.QRect(180, 480, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.create_butt.setFont(font)
        self.create_butt.setStyleSheet("QPushButton {\n"
                                       "    color: DarkBlue;\n"
                                       "    border: 3px solid bleak;\n"
                                       "    border-radius: 20px;\n"
                                       "    background-color: rgb(238, 238, 238);\n"
                                       "    text-align: center; /* Выравнивание текста по центру по вертикали */\n"
                                       "    padding: 5; /* Удаление внутренних отступов */\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover {\n"
                                       "    background-color: white;\n"
                                       "}\n"
                                       "")
        self.create_butt.setObjectName("create_butt")
        self.passport_text = QtWidgets.QLineEdit(self.centralwidget)
        self.passport_text.setGeometry(QtCore.QRect(250, 270, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.passport_text.setFont(font)
        self.passport_text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.passport_text.setStyleSheet("color: DarkBlue ;\n"
                                         "border: 3px solid bleak;\n"
                                         "border-radius: 20px;\n"
                                         "background-color: rgb(238, 238, 238);")
        self.passport_text.setAlignment(QtCore.Qt.AlignCenter)
        self.passport_text.setObjectName("passport_text")
        self.phone_text_ = QtWidgets.QLineEdit(self.centralwidget)
        self.phone_text_.setGeometry(QtCore.QRect(250, 210, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.phone_text_.setFont(font)
        self.phone_text_.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.phone_text_.setStyleSheet("color: DarkBlue ;\n"
                                       "border: 3px solid bleak;\n"
                                       "border-radius: 20px;\n"
                                       "background-color: rgb(238, 238, 238);")
        self.phone_text_.setAlignment(QtCore.Qt.AlignCenter)
        self.phone_text_.setObjectName("phone_text_")
        self.passport_label = QtWidgets.QLabel(self.centralwidget)
        self.passport_label.setGeometry(QtCore.QRect(70, 270, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.passport_label.setFont(font)
        self.passport_label.setStyleSheet("color: DarkBlue ;\n"
                                          "border: 3px solid bleak;\n"
                                          "border-radius: 20px;\n"
                                          "background-color: rgb(238, 238, 238);")
        self.passport_label.setAlignment(QtCore.Qt.AlignCenter)
        self.passport_label.setObjectName("passport_label")
        self.phone_label = QtWidgets.QLabel(self.centralwidget)
        self.phone_label.setGeometry(QtCore.QRect(70, 210, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.phone_label.setFont(font)
        self.phone_label.setStyleSheet("color: DarkBlue ;\n"
                                       "border: 3px solid bleak;\n"
                                       "border-radius: 20px;\n"
                                       "background-color: rgb(238, 238, 238);")
        self.phone_label.setAlignment(QtCore.Qt.AlignCenter)
        self.phone_label.setObjectName("phone_label")
        self.adress_label = QtWidgets.QLabel(self.centralwidget)
        self.adress_label.setGeometry(QtCore.QRect(70, 330, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.adress_label.setFont(font)
        self.adress_label.setStyleSheet("color: DarkBlue ;\n"
                                        "border: 3px solid bleak;\n"
                                        "border-radius: 20px;\n"
                                        "background-color: rgb(238, 238, 238);")
        self.adress_label.setAlignment(QtCore.Qt.AlignCenter)
        self.adress_label.setObjectName("adress_label")
        self.adress_text = QtWidgets.QLineEdit(self.centralwidget)
        self.adress_text.setGeometry(QtCore.QRect(250, 330, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.adress_text.setFont(font)
        self.adress_text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.adress_text.setStyleSheet("color: DarkBlue ;\n"
                                       "border: 3px solid bleak;\n"
                                       "border-radius: 20px;\n"
                                       "background-color: rgb(238, 238, 238);")
        self.adress_text.setAlignment(QtCore.Qt.AlignCenter)
        self.adress_text.setObjectName("adress_text")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(70, 390, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.password_label.setFont(font)
        self.password_label.setStyleSheet("color: DarkBlue ;\n"
                                          "border: 3px solid bleak;\n"
                                          "border-radius: 20px;\n"
                                          "background-color: rgb(238, 238, 238);")
        self.password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.password_label.setObjectName("password_label")
        self.password_text = QtWidgets.QLineEdit(self.centralwidget)
        self.password_text.setGeometry(QtCore.QRect(250, 390, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.password_text.setFont(font)
        self.password_text.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.password_text.setStyleSheet("color: DarkBlue ;\n"
                                         "border: 3px solid bleak;\n"
                                         "border-radius: 20px;\n"
                                         "background-color: rgb(238, 238, 238);")
        self.password_text.setText("")
        self.password_text.setAlignment(QtCore.Qt.AlignCenter)
        self.password_text.setObjectName("password_text")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.create_butt.clicked.connect(lambda: create_user_win_defes.create_user(self))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Створення профілю"))
        self.first_name_label.setText(_translate("MainWindow", "Ім\'я"))
        self.last_name_label.setText(_translate("MainWindow", "Прізвище"))
        self.create_butt.setText(_translate("MainWindow", "Створити"))
        self.passport_label.setText(_translate("MainWindow", "Номер паспорта"))
        self.phone_label.setText(_translate("MainWindow", "Номер телефона"))
        self.adress_label.setText(_translate("MainWindow", "Адреса"))
        self.password_label.setText(_translate("MainWindow", "Пароль"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = create_user_win_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
